

### Login to get token
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "debug-user@test.com",
  "password": "password123"
}

> {%
    client.global.set("token", response.body.token);
    client.log("Token stored: " + response.body.token);
%}


###

### Get borrower by ID with authentication
GET http://localhost:4000/api/borrowers/2
Authorization: Bearer {{token}}

###




