server:
  port: 4000

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: borrower-service-route
              uri: http://loan-borrower-service:4001
              predicates:
                - Path=/api/borrowers/**
              filters:
                - JwtValidation

            - id: officer-admin-route
              uri: http://loan-officer-service:4002
              predicates:
                - Path=/admin/**
              filters:
                - StripPrefix=1
                - OfficerValidation

            - id: officer-borrower-route
              uri: http://loan-officer-service:4002
              predicates:
                - Path=/borrower/**
              filters:
                - StripPrefix=1
                - JwtValidation

            - id: officer-health-route
              uri: http://loan-officer-service:4002
              predicates:
                - Path=/api/health/**

            - id: api-docs-borrower-route
              uri: http://loan-borrower-service:4001
              predicates:
                - Path=/api-docs/borrower
              filters:
                - RewritePath=/api-docs/borrower,/v3/api-docs

            - id: api-auth-service-route
              uri: http://loan-auth-service:4005
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1



            - id: api-docs-auth-route
              uri: http://loan-auth-service:4005
              predicates:
                - Path=/api-docs/auth
              filters:
                - RewritePath=/api-docs/auth,/v3/api-docs

auth:
  service:
    url: http://loan-auth-service:4005